name: export-and-branch-solution

# Controls when the workflow will run
on:
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  export-from-dev:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: who-am-i action
        uses: microsoft/powerplatform-actions/who-am-i@v0
        with:
          environment-url: 'https://org74c41697.crm.dynamics.com/'
          user-name: 'admin@M365x22902777.onmicrosoft.com'
          password-secret: ${{ secrets.password }}

      - name: export-solution action
        uses: microsoft/powerplatform-actions/export-solution@v0
        with:
          environment-url: 'https://org74c41697.crm.dynamics.com/'
          user-name: 'admin@M365x22902777.onmicrosoft.com'
          password-secret: ${{ secrets.password }}
          solution-name: ALMLab
          solution-output-file: out/exported/ALMLab.zip

      - name: unpack-solution action
        uses: microsoft/powerplatform-actions/unpack-solution@v0
        with:
          solution-file: out/exported/ALMLab.zip
          solution-folder: out/solutions/ALMLab
          solution-type: 'Unmanaged'
          overwrite-files: true

      - name: branch-solution, prepare it for a PullRequest
        uses: microsoft/powerplatform-actions/branch-solution@v0
        with:
          solution-folder: out/solutions/ALMLab
          solution-target-folder: solutions/ALMLab
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-empty-commit: true
